---
on:
  push:
    branches:
      - master
name: Builds
jobs:
  release:
    name: Release
    runs-on: [self-hosted, heavy]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - run: cargo make release
      - run: ls -lH bin/mainnet-release.wasm
      - name: Upload the mainnet-release.wasm artifact
        uses: actions/upload-artifact@v2
        with:
          name: mainnet-release.wasm
          path: bin/mainnet-release.wasm
      - name: Update the latest release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: latest
          file: bin/mainnet-release.wasm
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update the latest tag
        uses: EndBug/latest-tag@latest
  debug:
    name: Debug
    runs-on: [self-hosted, heavy]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - run: make debug
      - run: ls -lH mainnet-debug.wasm
      - name: Upload the mainnet-debug.wasm artifact
        uses: actions/upload-artifact@v2
        with:
          name: mainnet-debug.wasm
          path: mainnet-debug.wasm
      - name: Update the latest release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: latest
          file: mainnet-debug.wasm
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update the latest tag
        uses: EndBug/latest-tag@latest
